# Generated by Django 5.0.3 on 2024-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_swaprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='floor',
            field=models.IntegerField(choices=[(0, '1층-1'), (-1, '1층-2'), (2, '2층')]),
        ),
    ]
